services:
  control:
    build:
      dockerfile: ./dockerfiles/control.Dockerfile
    volumes:
      - ./ansible:/ansible
    tty: true
    stdin_open: true
    working_dir: /ansible
    networks:
      - ansible-sandbox

  managed:
    build:
      dockerfile: ./dockerfiles/managed.Dockerfile
    deploy:
      mode: replicated
      replicas: 2
    networks:
      - ansible-sandbox

networks:
  ansible-sandbox:
